name: CI
on:
  push:
    branches: 
      - master
jobs:
  build:
    runs-on: ubuntu-18.04
    name: Dotnet build
    steps:
      - uses: actions/checkout@master
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.100'
      - run: |
          cd steam_retriever
          dotnet publish -c Release
          dotnet publish -c Release -r osx-x64 --self-contained=false
          dotnet publish -c Release -r win-x64 --self-contained=false
          mkdir ../release/
          mv bin/Release/netcoreapp3.1/publish/steam_retriever bin/Release/netcoreapp3.1/publish/steam_retriever.linux
          mv bin/Release/netcoreapp3.1/osx-x64/publish/steam_retriever bin/Release/netcoreapp3.1/publish/steam_retriever.macos
          mv bin/Release/netcoreapp3.1/win-x64/publish/steam_retriever.exe bin/Release/netcoreapp3.1/publish/steam_retriever.exe
          mv bin/Release/netcoreapp3.1/publish ../release/steam_retriever
          exit 0
