# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    # branches: [ main ]
    tags: v*
  pull_request:
    # branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v2.1.0
        with:
          # Optional SDK version(s) to use. If not provided, will install global.json version when available. Examples: 2.2.104, 3.1, 3.1.x
          dotnet-version: 6.0.x

      # Runs a set of commands using the runners shell
      - name: Build project
        run: |
          mkdir release/
          for i in steam epic; do
            cd "${i}_retriever"
            dotnet publish -c Release
            dotnet publish -c Release -r osx-x64 --self-contained=false
            dotnet publish -c Release -r win-x64 --self-contained=false
            mv "bin/Release/net6.0/publish/${i}_retriever"             "bin/Release/net6.0/publish/${i}_retriever.linux"
            mv "bin/Release/net6.0/osx-x64/publish/${i}_retriever"     "bin/Release/net6.0/publish/${i}_retriever.macos"
            mv "bin/Release/net6.0/win-x64/publish/${i}_retriever.exe" "bin/Release/net6.0/publish/${i}_retriever.exe"
            mv "bin/Release/net6.0/publish" "../release/${i}_retriever"
            cd ..
          done
          exit 0
          
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: retrievers
          path: |
            release/steam_retriever
            release/epic_retriever
            
      - name: Packaging
        run: |
          cd release
          tar czf retrievers.tgz steam_retriever epic_retriever
          
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: release/retrievers.tgz
